[package]
name = "vault-utils"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "=1.0.133", default_features = false, features = ["derive"] }
serde_json = { version = "=1.0.75", default_features = false, features = [ "std" ] }
